version: "3.8"
services:
  langflow:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7860
    depends_on:
      - postgres-langflow
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflowpass@postgres-langflow:5432/langflow
      - LANGFLOW_AUTO_LOGIN=False
      - LANGFLOW_SUPERUSER=admin
      - LANGFLOW_SUPERUSER_PASSWORD=Agent2025.!
      - LANGFLOW_SECRET_KEY=dBuuuB_FHLvU8T9eUNlxQF9ppqRxwWpXXQ42kM2_fb
      - LANGFLOW_NEW_USER_IS_ACTIVE=False
    volumes:
      - langflow-data:/app/langflow
  postgres-langflow:
    image: postgres:16
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflowpass
      POSTGRES_DB: langflow
    ports:
      - 5432
    volumes:
      - langflow-postgres:/var/lib/postgresql/data
volumes:
  langflow-postgres:
  langflow-data: